### ISSUE TITLE
Update NuGet Package

### ISSUE THREAD

**Issue by mayermart** [davidwhitney/System.Diagnostics.Abstractions#6]
Is there any chance updating the NuGet Package to contain the Abstractions for Process (Pullrequest #3 )

**Comment by davidwhitney** [comment]
Morning!

Yes 👍 

I've been away for a little while, but I'll get this done this morning.

**Comment by davidwhitney** [comment]
This is now done :)

**Comment by mayermart** [comment]
Thanks a lot 👍 :)
